##-- #/_docs



################################################################################

#! <x.>
#! {
#!   "ext": "i.ignore",
#!   "src": "index.ignore",
#!   "?a": { "tags": ["att"], "filter": ["tags"] },
#!   "#": "#"
#! }
#! //
#! __$$['##fn'] = () => function({ ...vars }={}) {
#!   __$$dd('d'); // ..
#! }
#! </x.>

################################################################################

#! ..

################################################################################



##-- index



################################################################################

name: AttJob
on: [push]
jobs:
  AttJob:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo "works!"
      - run: npm i
      - run: npm run test

################################################################################

#<x.a000>{"label": "", "tags": []}</x.a000>

################################################################################



##-- _tmpl:index
#! 
#! 
#! 
#! ################################################################################
#! 
#! #! FROM ubuntu:18.04
#! 
#! ################################################################################
#! 
#! #<x._tmpl>{"label": "", "tags": []}</x._tmpl>
#! 
#! ################################################################################
#! 
#! 
#! 
##-- a000:index

